### ISSUE TITLE
1.0.0 on NPM?

### ISSUE THREAD

**Issue by jorrit** [alevy/memjs#102]
According to package.json you've released version 1.0.0. However, the latest on NPM is still 0.10.2. Is 1.0.0 not official?

**Comment by alevy** [comment]
@jorrit this is the version we _plan_ to release to npm but want some time to let any bugs surface in the new interface. If you're able to use it from git, that'd be great!

**Comment by jorrit** [comment]
Thanks for your quick reply. I will try. My suggestion is to release a 1.0.0-beta or 1.0.0-rc to NPM, which is the more common way to let people know that you have finished a new release and are looking for some final tests.

**Comment by alevy** [comment]
@jorrit ah that's a good suggestion. Will do.

**Comment by alevy** [comment]
Done
