### ISSUE TITLE
Crash Trace

### ISSUE THREAD

**Issue by stabib** [alevy/memjs#54]
Hi,

I'm seeing this crash in my logs:

Mar 25 15:25:59 app/web.23:  MemJS: Server <67439.5b2bbe.us-east-4.heroku.prod.memcachier.com:11211> failed after (2) retries with error - write EPIPE 
Mar 25 15:25:59 app/web.23:  Trace 
Mar 25 15:25:59  app/web.23:      at addListener (events.js:179:15) 
Mar 25 15:25:59  app/web.23:      at once (events.js:204:8) 
Mar 25 15:25:59  app/web.23:      at Socket.<anonymous> (/app/node_modules/memjs/lib/memjs/server.js:100:12) 
Mar 25 15:25:59  app/web.23:      at Socket.<anonymous> (/app/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31) 
Mar 25 15:25:59  app/web.23:      at Socket.g (events.js:199:16) 
Mar 25 15:25:59  app/web.23:      at Socket.emit (events.js:129:20) 
Mar 25 15:25:59  app/web.23:      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:974:10)

Any ideas on what the issue could be? I'm using memjs 0.8.5.

**Comment by alevy** [comment]
`write EPIPE` implies that the server on the other side broke the connection. It could be an authentication error or other application error (like setting a value too large). We should add better logging when there is an error response from the server.

**Comment by stabib** [comment]
Thanks for the update.

**Comment by dterei** [comment]
Fixed, same issue as #65
