### ISSUE TITLE
.get() Doesn't Return Key

### ISSUE THREAD

**Issue by rdegges** [alevy/memjs#55]
Hi all,

Firstly, I really like this library. Very very nice to have something which is super simple and handles everything.

I just started using this in a production application, and noticed an issue when performing .get() requests -- the key value isn't returned properly as I'd expect.

Here's what I'm doing:

```javascript
var memjs = require('memjs');

var cache = memjs.Client.create();

setInterval(function() {
  cache.get('some-key', function(err, value, key) {
    if (err) throw err;
    console.log('key:', key.toString());
    console.log('value:', value.toString());
  });
}, 60000);
```

What I get is a proper value (as I'd expect), but no Key value returned (eg: 'some-key'). It feels like this is a bug, as the docs suggest that key should contain the returned key name.

**Comment by alevy** [comment]
Thanks for pointing this out! This is a bug in the _documentation_. The second parameter to the callback is supposed to be the value _flags_. There is currently no way in `memjs` to set flags for a value (although there should be), so this argument will almost certainly be empty (unless a different client set the value flags).
