### ISSUE TITLE
UPDATE DOCS

### ISSUE THREAD

**Issue by mikeljames** [alevy/memjs#60]
Pleas update docs to say it defaults to localhost.

I just added code to do this. Now deleted it. wasted time! :D

**Comment by alevy** [comment]
It is documented in the comment for `Client#create` (third paragraph in the generated documentation: http://amitlevy.com/projects/memjs/). Do you have a suggestion for specific changes to the documentation?

**Comment by mikeljames** [comment]
That's cool I missed out the link to the docs page, I was using the readme.md in the project.
