### ISSUE TITLE
Ability to list memcached keys?

### ISSUE THREAD

**Issue by PradatiusD** [alevy/memjs#61]
Hi Memjs team! 

Is there any way to list the current keys stored on a Memcached server using this module?

It would be great to be able to list the current keys, so that a dev could then target and delete/set the particular subset of keys that need refreshing.

Something like.

```js
var memjs = require('memjs')
var client = memjs.Client.create()

client.getKeys(function(err, keys) { 
  console.log(keys);  //would output  an array of keys indicating what is stored on memcache
})
```

Otherwise I or any other dev using this module will have to hammer Memcachier with all possibilities to ensure that a particular subset of keys have been updated.

It could also be that I just plain missed this functionality while reading through the `memjs.js` file, or that this can be done by manually logging in to the memcached server and doing this via the terminal.  Any guidance/additional documentation is greatly appreciated!

Thanks,
Daniel

**Comment by alevy** [comment]
Hey Danile, you didn't miss anything in `memjs`. Implementing this could be problematic. The only way in memcache to get a list of all keys is using one of the `stats` subcommands. It's not particularly well-documented, not universally supported (for example, MemCachier does not currently support it) and to the extent that it is, it's marked as experimental. _Moreover_, it's a very very expensive operation that could block all other requests on the server for time proportional to the number of keys (millions?).

Having said all that, it's still a potentially useful feature to add.

Meanwhile, for your own purposes, have you explored whether using an expiration on keys solves your particular problem?

**Comment by PradatiusD** [comment]
In my case I would be surprised if it went past 50,000 keys.

Unfortunately anyone on the product angle of my team week to week give me wildly different suggestions on how long to cache data (and what that data should include).

If this is a issue with memcached then it looks like moving to Redis would be better, as it [has regex lookups](http://redis.io/commands/KEYS) and seems to be [recommended](http://www.infoworld.com/article/2825890/application-development/why-redis-beats-memcached-for-caching.html) over memcached in most instances.

Thanks again for the reply!

**Comment by alevy** [comment]
The operating in Redis is also proportional to the number of keys, and redis is completely single-threade, so will even more likely block other requests for a long time. If that's your alternative, than, yeah, maybe implementing this for memjs wouldn't be such a bad idea.
