### ISSUE TITLE
Function Signatures are Non-Standard

### ISSUE THREAD

**Issue by iChip** [alevy/memjs#68]
I was hoping to use Bluebird to promisify certain library functions by found an issue where in some functions the final argument doesn't conform to the node convention of lastArg = callback(err,data)

**Comment by alevy** [comment]
@iChip Yes, I agree with this. See #50 and #53. Basically, we need to figure out a way to (a) extend the arguments in a backwards compatible way while keeping the callback the last argument (probably using a jQuery-like hash as the first argument) and (b) migrate to that pattern.

Happy to accept pull requests and open to specific suggestions.

**Comment by alevy** [comment]
Duplicate of #53
