### ISSUE TITLE
Travis fails for stable nodejs due to compilation problems

### ISSUE THREAD

**Issue by dterei** [alevy/memjs#84]
Before we even get to testing memjs on node stable, it fails on Travis-CI due to compilation issues. See here:

https://travis-ci.org/dterei/memjs/jobs/126579639

**Comment by alevy** [comment]
Solved by 5bd4a5df9d76f513c2f008978dc6bc15cbf436c2

**Comment by alevy** [comment]
Solved by 5bd4a5d
