### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by sheerun** [alevy/memjs#92]
I get following error when trying to get/set values with memjs, especially on frequent calls:

```
(node:82222) Warning: Possible EventEmitter memory leak detected. 11 timeout listeners added. Use emitter.setMaxListeners() to increase limit
```

**Comment by zaguini** [comment]
+1

**Comment by alevy** [comment]
That's not totally impossible under expected operation. If you have frequent calls that might accumulate before previous calls are done, the emitter queue could build up.

Which versions are each of you (@sheerun, @zaguini) using?

**Comment by zaguini** [comment]
Was an error in my configuration. Fixed.

**Comment by alevy** [comment]
@zaguini is there anything about the configuration error that might be useful to others to know about?
