### ISSUE TITLE
How can I know that the connection is successful?

### ISSUE THREAD

**Issue by Rikhart** [alevy/memjs#96]
I am using the "version": "0.10.2" of memjs, is there  a way(like a callback or an event) to know if a get succesfull connection? , I am working with external memcache server hosted on google this is my implementation:

var memjs = require('memjs');
  var client = memjs.Client.create("xxx.xxx.xxx.xxx:11211",{
    user:"user",
    password:"password",
    logger:console,
    retries: 4
  });

But I dont know when connection happen and the logger dont show nothing.

Thanks by yours answers (y)

**Comment by alevy** [comment]
Hi @Rikhart! The connection is established lazily, when you first make a request (and for each server separately, and will be re-established behind the scenes if the connection drops). The surest way to ensure you are connecting is to call `stats` (which will query each server) and wait for the callback.
